apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-public
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/part-of: talos-hetzner-capi
    app.kubernetes.io/managed-by: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - {{ .Values.hostname | default "kratos.cluster.samuelbagattin.com" | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kratos-public
          port: 80
          weight: 1
