apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kratos-public
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/part-of: talos-hetzner-capi
    app.kubernetes.io/managed-by: argocd
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - {{ .Values.hostname | default "kratos.cluster.samuelbagattin.com" | quote }}
  rules:
    - backendRefs:
        - name: kratos-public
          port: 80
