# Kubernetes Secret manifests for talos-hetzner-capi
#
# This is an UNENCRYPTED template. Do NOT commit real values to Git.
#
# Workflow:
#   1. Copy this file:  cp secrets.example.yaml secrets.sops.yaml
#   2. Replace REPLACE_ME placeholders with real values
#   3. Encrypt:         sops -e -i argocd/secrets/secrets.sops.yaml
#   4. Decrypt:         sops -d argocd/secrets/secrets.sops.yaml
#   5. Edit in-place:   sops argocd/secrets/secrets.sops.yaml
#
# The .sops.yaml in the repo root defines encryption rules (age public key).
# The age private key must be available as SOPS_AGE_KEY env var or in ~/.config/sops/age/keys.txt.
#
# Namespace resources are included so that a single `kubectl apply` creates
# both the namespaces and their secrets. SOPS leaves these untouched (no
# data/stringData fields). ArgoCD's CreateNamespace=true is idempotent with
# namespaces that already exist.
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: identity
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
type: Opaque
stringData:
  # Hetzner Cloud API token (from 1Password or hcloud context)
  token: REPLACE_ME
  # Hetzner network ID (numeric, e.g. "11887756") — get via: hcloud network list
  network: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age-key
  namespace: argocd
type: Opaque
stringData:
  # Full age private key (starts with AGE-SECRET-KEY-1...)
  age.agekey: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/samuelbagattin
  githubAppID: "REPLACE_ME"
  githubAppInstallationID: "REPLACE_ME"
  githubAppPrivateKey: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  # Cloudflare API token with Zone:DNS:Edit and Zone:Zone:Read permissions
  api-token: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: hydra-secrets
  namespace: identity
type: Opaque
stringData:
  secretsCookie: REPLACE_ME
  secretsSystem: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-secrets
  namespace: identity
type: Opaque
stringData:
  secretsCookie: REPLACE_ME
  secretsDefault: REPLACE_ME
  # Full OIDC providers JSON array — overrides ConfigMap at runtime
  # See: https://github.com/ory/kratos/issues/1535
  SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS: 'REPLACE_ME'
---
apiVersion: v1
kind: Secret
metadata:
  name: kratos-selfservice-ui-secrets
  namespace: identity
type: Opaque
stringData:
  secretsCookie: REPLACE_ME
  secretsCSRFCookie: REPLACE_ME
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-credentials
  namespace: observability
type: Opaque
stringData:
  # Password from CNPG-generated secret postgres-cluster-grafana in postgres namespace
  # Retrieve with: kubectl get secret postgres-cluster-grafana -n postgres -o jsonpath='{.data.password}' | base64 -d
  password: REPLACE_ME
