apiVersion: v2
name: metrics-server
description: Kubernetes metrics-server for resource usage metrics
version: 0.1.0
type: application

dependencies:
  - name: metrics-server
    version: 3.13.0
    repository: https://kubernetes-sigs.github.io/metrics-server
