apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  scopes: "[groups, email]"
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, accounts, *, *, allow
    p, role:org-admin, certificates, *, *, allow
    p, role:org-admin, gpgkeys, *, *, allow
    p, role:org-admin, exec, create, */*, allow
    p, role:org-admin, logs, get, */*, allow
    g, admin, role:org-admin
    g, samuel@samuelbagattin.com, role:org-admin
