apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  telemetry:
    accessLog:
      settings:
        - format:
            type: JSON
            json:
              start_time: "%START_TIME%"
              method: "%REQ(:METHOD)%"
              path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              protocol: "%PROTOCOL%"
              status: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              bytes_received: "%BYTES_RECEIVED%"
              bytes_sent: "%BYTES_SENT%"
              duration_ms: "%DURATION%"
              upstream_host: "%UPSTREAM_HOST%"
              downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
              request_id: "%REQ(X-REQUEST-ID)%"
              authority: "%REQ(:AUTHORITY)%"
              user_agent: "%REQ(USER-AGENT)%"
          sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - name: otlp-gateway-collector
                    namespace: envoy-gateway-system
                    port: 4317
                resources:
                  k8s.cluster.name: "hetzner"
                  service.name: "envoy-gateway"
                  log.source: "envoy-access-log"
