---
# Coraza WAF via proxy-wasm — applies to all traffic through the Gateway.
# Uses per_authority_directives to apply tuned rulesets per hostname:
# - gRPC services (ArgoCD, Hydra) get rule exclusions for binary protobuf
# - All other traffic gets the full OWASP CRS
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: coraza-waf
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
  wasm:
    - name: coraza-filter
      code:
        type: HTTP
        http:
          url: http://coraza-wasm-server.envoy-gateway-system.svc.cluster.local/coraza-proxy-wasm.wasm
          sha256: {{ .Values.waf.sha256 }}
      failOpen: {{ .Values.waf.failOpen }}
      config:
        directives_map:
          # Full OWASP CRS — applied to all HTTP traffic by default
          default:
            - "Include @recommended-conf"
            - "SecRuleEngine {{ .Values.waf.ruleEngine }}"
            - "SecDebugLogLevel 3"
            - "Include @crs-setup-conf"
            - "Include @owasp_crs/*.conf"
          # Tuned ruleset for gRPC + REST API services (ArgoCD, Hydra)
          # Excludes: 911100 (DELETE/PUT/PATCH methods), 920420 (content-type),
          #           920270 (null chars), 921150 (CRLF in body)
          grpc:
            - "Include @recommended-conf"
            - "SecRuleEngine {{ .Values.waf.ruleEngine }}"
            - "SecDebugLogLevel 3"
            - "Include @crs-setup-conf"
            - "Include @owasp_crs/*.conf"
            - "SecRuleRemoveById 911100"
            - "SecRuleRemoveById 920420"
            - "SecRuleRemoveById 920270"
            - "SecRuleRemoveById 921150"
          # Tuned ruleset for Ory identity services (OIDC callbacks contain OAuth
          # scopes like "profile" which trigger LFI rule 930120 false positive)
          ory:
            - "Include @recommended-conf"
            - "SecRuleEngine {{ .Values.waf.ruleEngine }}"
            - "SecDebugLogLevel 3"
            - "Include @crs-setup-conf"
            - "Include @owasp_crs/*.conf"
            - "SecRuleRemoveById 930120"
          # Tuned ruleset for Grafana — disable response body inspection to
          # prevent Coraza WASM ProcessResponseBody bug causing HTTP/2 stream resets
          grafana:
            - "Include @recommended-conf"
            - "SecRuleEngine {{ .Values.waf.ruleEngine }}"
            - "SecDebugLogLevel 3"
            - "SecResponseBodyAccess Off"
            - "Include @crs-setup-conf"
            - "Include @owasp_crs/*.conf"
        default_directives: "default"
        per_authority_directives:
          argocd.cluster.samuelbagattin.com: "grpc"
          auth.cluster.samuelbagattin.com: "grpc"
          kratos.cluster.samuelbagattin.com: "ory"
          id.cluster.samuelbagattin.com: "ory"
          grafana.cluster.samuelbagattin.com: "grafana"
