apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: talos-hetzner-capi
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-server
  validation:
    caCertificateRefs:
      - name: argocd-server-tls
        group: ""
        kind: Secret
    hostname: argocd-server
