apiVersion: v2
name: cloudnative-pg
description: CloudNativePG operator for declarative PostgreSQL cluster management
version: 0.1.0
type: application

dependencies:
  - name: cloudnative-pg
    version: 0.27.0
    repository: https://cloudnative-pg.github.io/charts
