{{- /*
  Network policies for observability stack.

  The cluster-wide default-deny already allows:
  - Ingress from cluster entities
  - Egress to cluster, kube-apiserver, DNS, HTTPS (443)

  These policies add observability-specific rules beyond the defaults.
  Note: VMAgent kubelet scraping policy removed — OTel Collector has its own
  network policy in the otel-collectors app.
*/ -}}

---
# Grafana needs ingress from the Cilium Gateway (envoy proxy)
# for external access configured in Story 3.2.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana-allow-ingress
  labels:
    app.kubernetes.io/part-of: talos-hetzner-capi
    app.kubernetes.io/managed-by: argocd
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  ingress:
    - fromEntities:
        - cluster
        - ingress
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
