apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hydra
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/part-of: talos-hetzner-capi
    app.kubernetes.io/managed-by: argocd
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - {{ .Values.hostname | default "auth.cluster.samuelbagattin.com" | quote }}
  rules:
    - backendRefs:
        - name: hydra-public
          port: 4444
