apiVersion: v2
name: kube-image-keeper
description: Container image routing and replication for Kubernetes
version: 0.1.0
type: application

dependencies:
  - name: kube-image-keeper
    version: 2.0.0
    repository: oci://quay.io/enix/charts
